### ISSUE TITLE
Unable to create nested modules

### ISSUE THREAD

**Issue by webz2feel** [nWidart/nwidart-docs#30]
i want to group modules further, for example i want to create sub folder inside main Module directory then create modules inside that directory e.g Modules/Core/Base, Modules/Core/Setting etc. but whenever i run command php artisan module:make Core/Base it throw an error  Nwidart\Modules\Exceptions\ModuleNotFoundException  : Module [Core/Base] does not exist!
how i can group nested modules. Thanks!

**Comment by nWidart** [comment]
Hi, 

This is not supported, I don't recommend doing this. I would advise to separate modules on one level only.
