### ISSUE TITLE
Laravel 7 Blade Components 

### ISSUE THREAD

**Issue by virgiltu** [nWidart/nwidart-docs#32]
While I do not really know laravel well enough to add this myself, I wanted to see if there was still a plan to add latavel 7 blade components. 

 https://laracasts.com/series/whats-new-in-laravel-7/episodes/1

**Comment by virgiltu** [comment]
Update on this the module does not work with Laravel 7 

`D:\laravel\istyle\Sync\istyle\Server\www\FrontEnd>php artisan module:make-model mobile

   Error 

  Class 'Modules\Mobile\Providers\MobileServiceProvider' not found

  at D:\laravel\istyle\Sync\istyle\Server\www\FrontEnd\vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php:208
    204|      * @return \Illuminate\Support\ServiceProvider
    205|      */
    206|     public function createProvider($provider)
    207|     {
  > 208|         return new $provider($this->app);
    209|     }
    210| }
    211| 

  1   D:\laravel\istyle\Sync\istyle\Server\www\FrontEnd\vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php:144
      Illuminate\Foundation\ProviderRepository::createProvider("Modules\Mobile\Providers\MobileServiceProvider")

  2   D:\laravel\istyle\Sync\istyle\Server\www\FrontEnd\vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php:61
      Illuminate\Foundation\ProviderRepository::compileManifest()`

**Comment by nWidart** [comment]
Hello,

Blade components are not linked to this package, you can just use them as referenced by the docs.
The error you have seems to be with how you autoloaded the modules. Make sure you did so.

I'm running the package in laravel 7 and it works fine.

**Comment by virgiltu** [comment]
> Hello,
> 
> Blade components are not linked to this package, you can just use them as referenced by the docs.
> The error you have seems to be with how you autoloaded the modules. Make sure you did so.
> 
> I'm running the package in laravel 7 and it works fine.

I will run it again, this was a clean L7 setup with just the modules. I can create modules, but I can not add models.

**Comment by virgiltu** [comment]
> Hello,
> 
> Blade components are not linked to this package, you can just use them as referenced by the docs.
> The error you have seems to be with how you autoloaded the modules. Make sure you did so.
> 
> I'm running the package in laravel 7 and it works fine.

Just did a new setup and the same thing. Everything works but not when I try to create a model. Also not sure if makes a difference, the install is Laravel 7.3.0. I will roll back to 7 to see. 



D:\laravel\istyle\Sync\istyle\Server\www\FrontEnd>php artisan module:make-model -m  home

   Error 

  Class 'Modules\Home\Providers\HomeServiceProvider' not found

  at D:\laravel\istyle\Sync\istyle\Server\www\FrontEnd\vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php:208
    204|      * @return \Illuminate\Support\ServiceProvider
    205|      */
    206|     public function createProvider($provider)
    207|     {
  > 208|         return new $provider($this->app);
    209|     }
    210| }
    211| 

  1   D:\laravel\istyle\Sync\istyle\Server\www\FrontEnd\vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php:144
      Illuminate\Foundation\ProviderRepository::createProvider("Modules\Home\Providers\HomeServiceProvider")

  2   D:\laravel\istyle\Sync\istyle\Server\www\FrontEnd\vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php:61
      Illuminate\Foundation\ProviderRepository::compileManifest()

D:\laravel\istyle\Sync\istyle\Server\www\FrontEnd>
