### ISSUE TITLE
problem with publishing automatically module in Modules/ folder

### ISSUE THREAD

**Issue by emiolo** [nWidart/nwidart-docs#4]
Hello!
I am having a problem when I try to install some module automatically through composer.json using "joshbrw/laravel-module-installer".
The repository is deprived of Bitbucket, usually downloaded, but the "Modules/" folder is added as "Modules/" again instead of adding the real name of the module (eg ApiModule), ie this "Modules/Modules/", should be "Modules/ApiModule/". If you can help.

Here are the codes:

No composer.json (root):
"Require": {
     ....
       "Nwidart / laravel-modules": "^ 1.19",
       "Joshbrw / laravel-module-installer": "v0.1.2",
       "Xxxxx / api-module": "*",
     ....
},
"Repositories": [
        {
            "Type": "package",
            "Package": {
                "Name": "xxxxx / api-module",
                "Version": "0.0.1",
                "Type": "laravel-module",
                "Source": {
                    "Url": "git@bitbucket.org: xxxxx / api-module.git",
                    "Type": "git",
                    "Reference": "origin / master"
                }
            }
        }
    ],

In the composer.json (from the module):
"Type": "laravel-module",

What am I doing wrong?
Thanks!

**Comment by nWidart** [comment]
Hello,

Please post this in nwidart/laravel-modules, thanks!
