### ISSUE TITLE
Events / Listeners

### ISSUE THREAD

**Issue by lmarcelocc** [nWidart/nwidart-docs#7]
Hi,

it's supposed to add to `EventServiceProvider.php`, the events created in modules folder? Is this the best way?

Thanks.

Best regards, 
Marcelo

**Comment by nWidart** [comment]
Hello,

That's how I would do it, yes. The goal is to have everything belonging together, grouped together in a module.

**Comment by lmarcelocc** [comment]
Hi nWidart,

thank you very much!

Cheers
